"""evaluator.py -- AST -> Z3 expression evaluator (SymbolicEvaluator).

(Auto-extracted verbatim from the original monolith during modularization.)
"""

from __future__ import annotations

import ast
import z3
try:
    from .ast_extractor import CFGExtractor, _unparse
except ImportError:
    from ast_extractor import CFGExtractor, _unparse
from .registry import Z3VariableRegistry


class SymbolicEvaluator(ast.NodeVisitor):
    """
    Convert a Python expression AST into an equivalent Z3 expression.

    Supports the subset most commonly generated by LLMs for workflow
    conditions: literals, names, arithmetic, comparisons, and boolean
    connectives.
    """

    def __init__(
        self,
        registry: Z3VariableRegistry,
        symbolic_state: dict[str, z3.ExprRef],
    ) -> None:
        self.registry = registry
        self.symbolic_state = symbolic_state

    def eval(self, node: ast.AST) -> z3.ExprRef:
        """Entry point -- dispatch to ``visit_*``."""
        method = getattr(self, f"visit_{type(node).__name__}", self.generic_visit)
        return method(node)

    def generic_visit(self, node: ast.AST) -> z3.ExprRef:
        raise NotImplementedError(
            f"Symbolic evaluation not supported for {type(node).__name__}"
        )

    # -- literals --------------------------------------------------------

    def visit_Constant(self, node: ast.Constant) -> z3.ExprRef:
        v = node.value
        if isinstance(v, bool):
            return z3.BoolVal(v)
        elif isinstance(v, int):
            return z3.IntVal(v)
        elif isinstance(v, float):
            return z3.RealVal(v)
        elif isinstance(v, str):
            # String-as-token encoding.
            return z3.IntVal(hash(v) & 0x7FFFFFFF)
        else:
            sort = self.registry.infer_sort(v)
            return z3.Const(f"const_{id(v)}", sort)

    def visit_Name(self, node: ast.Name) -> z3.ExprRef:
        if node.id in self.symbolic_state:
            return self.symbolic_state[node.id]
        reg = self.registry.get(node.id)
        if reg is not None:
            return reg
        # Undeclared name -- create an uninterpreted placeholder.
        placeholder = z3.Const(node.id, z3.DeclareSort("PyObject"))
        self.symbolic_state[node.id] = placeholder
        return placeholder

    # -- arithmetic ------------------------------------------------------

    def visit_BinOp(self, node: ast.BinOp) -> z3.ExprRef:
        left = self.eval(node.left)
        right = self.eval(node.right)

        if isinstance(node.op, ast.Add):
            return left + right
        elif isinstance(node.op, ast.Sub):
            return left - right
        elif isinstance(node.op, ast.Mult):
            return left * right
        elif isinstance(node.op, ast.Div):
            return left / right
        elif isinstance(node.op, ast.FloorDiv):
            # Z3 has no native floor-div; approximate with ToReal/ToInt.
            return z3.ToInt(left / right)
        elif isinstance(node.op, ast.Mod):
            return left % right
        elif isinstance(node.op, ast.Pow):
            # Z3 has no native power for integers; keep uninterpreted.
            sort = z3.IntSort() if left.sort() == z3.IntSort() else z3.RealSort()
            return z3.Const(f"pow_{id(node)}", sort)
        else:
            raise NotImplementedError(f"BinOp {type(node.op).__name__}")

    # -- comparisons -----------------------------------------------------

    def visit_Compare(self, node: ast.Compare) -> z3.ExprRef:
        left = self.eval(node.left)
        result: list[z3.BoolRef] = []

        for op, comparator in zip(node.ops, node.comparators):
            right = self.eval(comparator)
            if isinstance(op, ast.Eq):
                result.append(left == right)
            elif isinstance(op, ast.NotEq):
                result.append(left != right)
            elif isinstance(op, ast.Lt):
                result.append(left < right)
            elif isinstance(op, ast.LtE):
                result.append(left <= right)
            elif isinstance(op, ast.Gt):
                result.append(left > right)
            elif isinstance(op, ast.GtE):
                result.append(left >= right)
            else:
                result.append(z3.BoolVal(True))  # fallback
            left = right  # chained comparison semantics

        if len(result) == 1:
            return result[0]
        return z3.And(*result)

    # -- boolean connectives ---------------------------------------------

    def visit_BoolOp(self, node: ast.BoolOp) -> z3.ExprRef:
        vals = [self.eval(v) for v in node.values]
        if isinstance(node.op, ast.And):
            return z3.And(*vals)
        elif isinstance(node.op, ast.Or):
            return z3.Or(*vals)
        else:
            raise NotImplementedError(f"BoolOp {type(node.op).__name__}")

    def visit_UnaryOp(self, node: ast.UnaryOp) -> z3.ExprRef:
        val = self.eval(node.operand)
        if isinstance(node.op, ast.Not):
            return z3.Not(val)
        elif isinstance(node.op, ast.UAdd):
            return +val
        elif isinstance(node.op, ast.USub):
            return -val
        else:
            raise NotImplementedError(f"UnaryOp {type(node.op).__name__}")

    def visit_NamedExpr(self, node: ast.NamedExpr) -> z3.ExprRef:
        """Walrus operator: evaluate RHS and bind to target symbolically."""
        value = self.eval(node.value)
        target_name = node.target.id if isinstance(node.target, ast.Name) else _unparse(node.target)
        self.symbolic_state[target_name] = value
        return value

    def visit_Call(self, node: ast.Call) -> z3.ExprRef:
        """
        Function calls are treated as uninterpreted functions.
        We create a fresh constant whose sort is inferred from the
        function name heuristic (e.g. ``len`` -> IntSort).
        """
        func_name = _unparse(node.func)
        # Simple heuristic: len -> Int, anything else -> generic.
        sort = z3.IntSort() if func_name == "len" else z3.DeclareSort("PyObject")
        return z3.Const(f"call_{func_name}_{id(node)}", sort)

    def visit_Subscript(self, node: ast.Subscript) -> z3.ExprRef:
        """e.g. ``order["total"]`` -- look up in flattened registry."""
        base = _unparse(node.value)
        idx = _unparse(node.slice)
        flat_key = f"{base}_{idx}"
        flat = self.registry.get_flat(flat_key)
        if flat is not None:
            return flat
        # Fallback: array select if base is an Array.
        if base in self.symbolic_state:
            arr = self.symbolic_state[base]
            if isinstance(arr, z3.ArrayRef):
                index_expr = self.eval(node.slice)
                return z3.Select(arr, index_expr)
        return z3.Const(flat_key, z3.DeclareSort("PyObject"))
