services:
  spec-engine:
    build:
      context: ./module_01_spec
    container_name: spec-engine

  extract-engine:
    build:
      context: ./module_02_extract
    container_name: extract-engine
    volumes:
      - ./shared_schemas:/app/shared_schemas:ro

  equiv-engine:
    build:
      context: ./module_03_equiv
    container_name: equiv-engine

  ui-engine:
    build:
      context: ./module_04_ui
    container_name: ui-engine
    volumes:
      - ./module_04_ui:/app
      - ./module_01_spec:/module_01_spec
    ports:
      - "8501:8501"
